In [2]:
pip install opencv-python


   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   ---------------------------------------- 0.1/38.8 MB 1.7 MB/s eta 0:00:24
   ---------------------------------------- 0.1/38.8 MB 1.2 MB/s eta 0:00:32
   ---------------------------------------- 0.2/38.8 MB 1.5 MB/s eta 0:00:26
   ---------------------------------------- 0.2/38.8 MB 1.3 MB/s eta 0:00:30
   ---------------------------------------- 0.2/38.8 MB 1.3 MB/s eta 0:00:30
   ---------------------------------------- 0.2/38.8 MB 1.3 MB/s eta 0:00:30
   ---------------------------------------- 0.3/38.8 MB 774.0 kB/s eta 0:00:50
   ---------------------------------------- 0.3/38.8 MB 774.0 kB/s eta 0:00:50
   ---------------------------


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
import cv2
from PIL import Image

In [55]:
img= cv2.imread("./../output_image.png")
img_arr = np.array(img)
img_arr.shape

(9622, 25231, 3)

In [56]:
leng = img_arr.shape[0]/10
bred = img_arr.shape[1]/10
leng=int(leng)
bred= int(bred)
leng,bred

(962, 2523)

In [57]:
img_reszied= cv2.resize(img, (bred, leng))
img_reszied.shape

(962, 2523, 3)

In [58]:
img_array = np.array(img_reszied)
img_array.shape

(962, 2523, 3)

In [59]:
img_array

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [60]:
img_gray = cv2.cvtColor(img_reszied, cv2.COLOR_BGR2GRAY)
img_gray.shape

(962, 2523)

In [61]:
img_gray

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [62]:
img_normalize= img_gray / 255.0
img_normalize

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [64]:
img_normalize_uint8 = (img_normalize * 255).astype(np.uint8)
img_normalize_uint8

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [65]:
img= Image.fromarray(img_normalize_uint8)
img.save("proprocessed.jpg")

Dont know if this big images gonna work... lets test it out later!